# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.device.bacnet}}
  name: {{.Values.edgex.app.device.bacnet}}
spec:
  ports:
  - name: "device-bacnet-http"
    port: {{.Values.edgex.port.device.bacnet}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.device.bacnet}}
  type: {{.Values.expose.type.device.bacnet}}

