# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.appservice.metricsinfluxdb}}
  name: {{.Values.edgex.app.appservice.metricsinfluxdb}}
spec:
  ports:
  - name: "app-metrics-influxdb-http"
    port: {{.Values.edgex.port.appservice.metricsinfluxdb}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.appservice.metricsinfluxdb}}
  type: {{.Values.expose.type.appservice.metricsinfluxdb}}
