[Writable]
LogLevel = 'INFO'

[Service]
HealthCheckInterval = '10s'
Host = 'localhost'
Port = 59780 # Adjust if running multiple examples at the same time to avoid duplicate port conflicts
ServerBindAddr = "" # if blank, uses default Go behavior https://golang.org/pkg/net/#Listen
StartupMsg = 'Custom Trigger Example'
MaxResultCount = 0 # Not curently used by App Services.
MaxRequestSize = 0 # Not curently used by App Services.
RequestTimeout = '5s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Trigger]
Type="custom-stdin"
