# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-config
spec:
  {{- if (eq .Values.edgex.storage.useHostPath true)}}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{.Values.edgex.storage.nonSharedVolumesClassName}}"
  {{- end }}
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  resources:
    requests:
      storage: 8Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data
spec:
  {{- if (eq .Values.edgex.storage.useHostPath true)}}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{.Values.edgex.storage.nonSharedVolumesClassName}}"
  {{- end }}
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
spec:
  {{- if (eq .Values.edgex.storage.useHostPath true)}}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{.Values.edgex.storage.nonSharedVolumesClassName}}"
  {{- end }}
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuiper-data
spec:
  {{- if (eq .Values.edgex.storage.useHostPath true)}}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{.Values.edgex.storage.nonSharedVolumesClassName}}"
  {{- end }}
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuiper-etc
spec:
  {{- if (eq .Values.edgex.storage.useHostPath true)}}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{.Values.edgex.storage.nonSharedVolumesClassName}}"
  {{- end }}
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  resources:
    requests:
      storage: 8Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuiper-log
spec:
  {{- if (eq .Values.edgex.storage.useHostPath true)}}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{.Values.edgex.storage.nonSharedVolumesClassName}}"
  {{- end }}
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuiper-plugins
spec:
  {{- if (eq .Values.edgex.storage.useHostPath true)}}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{.Values.edgex.storage.nonSharedVolumesClassName}}"
  {{- end }}
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  resources:
    requests:
      storage: 128Mi
{{- if (gt (.Values.edgex.replicas.natsserver | int) 0) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-data
spec:
  {{- if (eq .Values.edgex.storage.useHostPath true)}}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{.Values.edgex.storage.nonSharedVolumesClassName}}"
  {{- end }}
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  resources:
    requests:
      storage: 128Mi
{{- end }}
{{- if (gt (.Values.edgex.replicas.appservice.rfidllrpinventory | int) 0) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llrp-inventory-data
spec:
  {{- if (eq .Values.edgex.storage.useHostPath true)}}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{.Values.edgex.storage.nonSharedVolumesClassName}}"
  {{- end }}
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  resources:
    requests:
      storage: 128Mi
{{- end }}
