[Writable]
LogLevel = "DEBUG"
[Writable.StoreAndForward]
  Enabled = false
  RetryInterval = "5m"
  MaxRetryCount = 10
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
    path = "redisdb"
      [Writable.InsecureSecrets.DB.Secrets]
      username = ""
      password = ""
  [Writable.Telemetry]
  Interval = "0s" # Disabled since require MessageBus Trigger to be in use.

[Service]
HealthCheckInterval = "10s"
Host = "localhost"
ServerBindAddr = "" # if blank, uses default Go behavior https://golang.org/pkg/net/#Listen
Port = 59780 # Adjust if running multiples examples at the same time to avoid duplicate port conflicts
StartupMsg = "Cloud Event Transforms"
RequestTimeout = "30s"
MaxRequestSize = 0
MaxResultCount = 0
  [Service.CORSConfiguration]
  EnableCORS = false
  CORSAllowCredentials = false
  CORSAllowedOrigin = "https://localhost"
  CORSAllowedMethods = "GET, POST, PUT, PATCH, DELETE"
  CORSAllowedHeaders = "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID"
  CORSExposeHeaders = "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
  CORSMaxAge = 3600

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

[Database]
Type = "redisdb"
Host = "localhost"
Port = 6379
Timeout = "30s"

[Clients]
  [Clients.core-metadata]
  Protocol = "http"
  Host = "localhost"
  Port = 59881

[SecretStore]
  Type = "vault"
  Protocol = "http"
  Host = "localhost"
  Port = 8200
  Path = "app-cloud-event/"
  TokenFile = "/tmp/edgex/secrets/app-cloud-event/secrets-token.json"
  RootCaCertPath = ""
  ServerName = ""
  [SecretStore.Authentication]
    AuthType = "X-Vault-Token"

# This example expect custom type via HTTP Trigger
[Trigger]
Type="http"

[ApplicationSettings]
