[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'Azure IoT Export Service'
Timeout = '5s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

[Logging]
EnableRemote = false
File = ''

[Binding]
Type="messagebus"
SubscribeTopic="events"
PublishTopic=""

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

[ApplicationSettings]
IoTHub         = "EdgeX"
IoTDevice      = "TestDevice01"
MQTTCert       = "/secret/rsa_cert.pem"
MQTTKey        = "/secret/rsa_private.pem"
TokenPath      = "/secret/secrets-token.json"
VaultHost      = "localhost"
VaultPort      = "8200"
CertPath       = "v1/secret/edgex/edgex-application-service/iothub"
DeviceNames    = "Random-Integer-Device"
