# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Pre-define Devices
[[DeviceList]]
    Name = "edge-video-analytics"
    ProfileName = "edge-video-analytics-profile"
    Description = "Device for EVAM (Edge Video Analytics Microservice) pipeline events"
    Labels = ["cv", "dlstreamer", "evam", "pipeline-server", "edge-video-analytics"]
    [DeviceList.Protocols]
        [DeviceList.Protocols.mqtt]
            CommandTopic = "command/edge-video-analytics"
