# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgex-common-variables
data:
{{- if .Values.edgex.security.enabled }}
  EDGEX_SECURITY_SECRET_STORE: "true"
  SECRETSTORE_HOST: edgex-vault
  STAGEGATE_WAITFOR_TIMEOUT: "60s"
  STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
  STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
  STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
  STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
  # this is intended to be the same as Database.Host/.Port for other services
  STAGEGATE_DATABASE_HOST: edgex-redis
  STAGEGATE_DATABASE_PORT: "6379"
  STAGEGATE_DATABASE_READYPORT: "6379"
  # this is intended to be the same as Registry.Host/.Port for other services
  STAGEGATE_REGISTRY_HOST: edgex-core-consul
  STAGEGATE_REGISTRY_PORT: "8500"
  STAGEGATE_REGISTRY_READYPORT: "54324"
  STAGEGATE_READY_TORUNPORT: "54329"
  PROXY_SETUP_HOST: edgex-security-proxy-setup
{{- else }}
  EDGEX_SECURITY_SECRET_STORE: "false"
{{- end }}
